In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
Migrants = pd.read_csv('./MissingMigrants-Global-2019-12-31_correct.csv', sep = ',')
Migrants

,Web ID,Region of Incident,Reported Date,Reported Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Location Description,Information Source,Location Coordinates,Migration Route,URL,UNSD Geographical Grouping,Source Quality
0,52673,Mediterranean,"December 30, 2019",2019,Dec,1.0,NaN,1,11.0,NaN,NaN,NaN,Hypothermia,Unspecififed location off the coast of Algeria,El Watan,"35.568972356329, -1.289773129748",Western Mediterranean,https://bit.ly/2FqQHo4,Uncategorized,1
1,52666,Mediterranean,"December 30, 2019",2019,Dec,1.0,NaN,1,NaN,NaN,1.0,NaN,Presumed drowning,"Recoverd on Calamorcarro Beach, Ceuta",El Foro de Ceuta,"35.912383552874, -5.357673338898",Western Mediterranean,https://bit.ly/39yKRyF,Uncategorized,1
2,52663,East Asia,"December 27, 2019",2019,Dec,5.0,NaN,5,NaN,NaN,3.0,NaN,Unknown,"Bodies found on boat near Sado Island, Niigata...","Japan Times, Kyodo News, AFP","38.154018233313, 138.086032653130",NaN,"http://bit.ly/2sCnBz1, http://bit.ly/2sEra83, ...",Eastern Asia,3
3,52662,Middle East,"December 26, 2019",2019,Dec,7.0,NaN,7,64.0,NaN,NaN,NaN,Drowning,"Van lake near Adilcevaz, Bitlis, Turkey","EFE, BBC, ARYnews","38.777228612085, 42.739257582031",NaN,"http://bit.ly/2ZG2Y19, http://bit.ly/2MLamDf, ...",Western Asia,3
4,52661,Middle East,"December 24, 2019",2019,Dec,12.0,NaN,12,NaN,NaN,NaN,NaN,Air strike,"Al-Raqw market in Saada, Yemen","UN Humanitarian Coordinator in Yemen, Qatar Tr...","17.245364805636, 43.239093360326",NaN,"http://bit.ly/2FjolvD, http://bit.ly/2sD42GR, ...",Western Asia,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5982,39207,US-Mexico Border,"January 16, 2014",2014,Jan,1.0,NaN,1,NaN,NaN,1.0,NaN,Shot,"near Douglas, Arizona",Ministry of Foreign Affairs Mexico,"31.344700000000, -109.545000000000",Central America to US,http://bit.ly/1qfIw00,Northern America,5
5983,39368,Europe,"January 16, 2014",2014,Jan,1.0,0.0,1,2.0,NaN,1.0,NaN,Hyperthermia,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.155100000000, 27.858600000000",NaN,http://bit.ly/1rTFTjR,Northern Europe,1
5984,39257,US-Mexico Border,"January 14, 2014",2014,Jan,1.0,NaN,1,NaN,NaN,NaN,NaN,Unknown (skeletal remains),Pima County,Pima County Office of the Medical Examiner,"32.058118300000, -111.623576100000",Central America to US,NaN,Northern America,5
5985,39256,US-Mexico Border,"January 12, 2014",2014,Jan,1.0,NaN,1,NaN,NaN,NaN,NaN,Unknown (skeletal remains),Pima County,Pima County Office of the Medical Examiner,"32.058118300000, -111.623576100000",Central America to US,NaN,Northern America,5
5986,39206,US-Mexico Border,"January 06, 2014",2014,Jan,1.0,NaN,1,NaN,NaN,1.0,NaN,Unknown (skeletal remains),Pima County,Humane Borders Arizona Open GIS Initiative,"32.058118300000, -111.623576100000",Central America to US,http://humaneborders.info/,Northern America,5

In [34]:
Migrants.groupby('Cause of Death').count()[['Location Description']]

                                         Location Description
Cause of Death
Accident (non-vehicle)                                      3
Air strike                                                  3
Asphyxiation                                               11
Asphyxiation, Drowning                                      2
Attacked by Apache helicopter                               1
...                                                       ...
Vehicle Accident, Shot, Stabbed                             1
Violence                                                   50
Violence while attempting to board boat                     1
Violence, Asphyxiation, Drowning                            1
Violence, Rape                                              1

[266 rows x 1 columns]

In [35]:
Migrants = Migrants[Migrants['Cause of Death']=='Unknown']
Migrants.groupby('Number Dead').count()['Cause of Death']

Number Dead
0.0        1
1.0      479
2.0       37
3.0       31
4.0       10
5.0       10
6.0        7
7.0        5
8.0        9
9.0        3
10.0       8
13.0       3
14.0       2
15.0       1
18.0       2
24.0       1
36.0       1
106.0      1
Name: Cause of Death, dtype: int64

In [38]:
Migrants = Migrants[Migrants['Migration Route']=='Central America to US']
Migrants.groupby('Region of Incident').count()['Total Dead and Missing']

Region of Incident
Central America      20
US-Mexico Border    262
Name: Total Dead and Missing, dtype: int64

In [39]:
deaths = Migrants['Number Dead']
avg = np.round(deaths.mean(),2)
avg

1.09

In [46]:
fig, ax = plt.subplots(figsize=(16, 9)) #Subplots makes a call in the background to create a plot area
# generate random data
data = 'MissingMigrants-Global-2019-12-31_correct.csv'
plt.hist(data, bins = 50, label = 'Data', color = 'r', alpha = 0.75)
plt.xticks(fontsize = 25)
plt.yticks(fontsize = 25)
plt.xlabel('Value', fontname = 'Sans serif', fontsize = 35)
plt.ylabel('Frequency', fontname = 'Sans serif', fontsize = 35)
plt.legend(loc = 'upper left', fontsize = 30)
plt.show()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 449: character maps to <undefined>